# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "33f92174ba4c976450f822330e875deb8fe7fb1d8d29b65051e5d9a6237d48f8"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eaceb6679ee7479ac1fc37e5f3745f101a62791f2331259a9c4505f366e6ee96"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf2574dbbc579f52930069564f238191b26b3822485a718a94dc42973ad15eda"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3221aefc3edaed4b58f5d104c6b0e3718471ca00750b137633d5207ebc4dd43"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "azctx"
  desc "Per-shell isolated Azure subscription contexts"
  homepage "https://github.com/iul1an/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end
  generate_completions_from_executable "azctx", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
