# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "13212164571a2e39a0ef9d0d302b62b03418e0c882072a1fb3966408eb12e78f"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5026c2f71bec9183ea96340fae2e46d1f781206194eb1e546bd7b74a45e12b6b"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53e360d37c08af05d272e11f096691a2e59aa17e4c1892f384da724b2cc213cf"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59f4b86d19e731b33dabbdfba9365365de0422e3918a92b46f9d80d7756ec33b"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "azctx"
  desc "Per-shell isolated Azure subscription contexts"
  homepage "https://github.com/iul1an/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end
  generate_completions_from_executable "azctx", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
