# This file was generated by GoReleaser. DO NOT EDIT.
cask "azctx" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "4c621159c5685c016c869e9f72388ff2881fdc55f76703e3f332c82f09e6c2f4"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5064304201ff8ce36cb4cb4300daf61d9f01470b1fcff802adfb7be357c0493f"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "857d4e622733dea95ef2ebc4037f11d12d992b827d8135beccc5f8854efb53d9"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5a81628810ea3448155a86b68399301594c6a71cc992d92fe1e48b2495abe50"
      url "https://github.com/iul1an/azctx/releases/download/v#{version}/azctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "azctx"
  desc "Per-shell isolated Azure subscription contexts"
  homepage "https://github.com/iul1an/azctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azctx"]
    end
  end
  generate_completions_from_executable "azctx", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
